server {
  listen 80;
  server_name dl.meowti.kr;

  root /srv/web/dl.meowti.kr/files;
  autoindex off;

  location = /healthz {
    access_log off;
    default_type text/plain;
    return 200 "ok\n";
  }

  # fixed endpoint for onboarding/download link
  location = /instance.zip {
    alias /srv/web/dl.meowti.kr/files/instances/instance.zip;
  }

  location / {
    try_files $uri =404;
  }

  sendfile on;
  tcp_nopush on;
}
