server {
  listen 80;
  server_name dl.meowti.kr;

  root /srv/web/dl.meowti.kr/files;
  autoindex off;

  location = /healthz {
    access_log off;
    add_header Content-Type text/plain;
    return 200 "ok\n";
  }

  location / {
    try_files $uri =404;
  }

  # Large file download stability
  sendfile on;
  tcp_nopush on;
}
